Correct capitalization of Arduino.h
Incorrect capitalization caused compilation to fail on filename case sensitive operating systems such as Linux:

fatal error: arduino.h: No such file or directory